### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by JustArchi**

### CODE REVIEW

**Comment by ecalfonso** [comment]
I really don't know why there are typos. Copypasta don't work

**Comment by JustArchi** [comment]
I don't know either, as I don't have these typos in my repos :+1:

**Comment by ecalfonso** [comment]
Very weird, but thank you for checking things for me! I really do appreciate all the work you've done

**Comment by JustArchi** [comment]
If I see an issue, I try to correct it. You're welcome :+1:

**Pull request merged**
